### ISSUE TITLE
 "Deprecated! since version 0.0.3. Please use scan_plugins_regex!"

### ISSUE THREAD

**Issue by chansdad** [chfw/lml#16]
Receiving this warning when trying out the v2 example . Any suggestions on fixing it ?
$robotchef_v2 "Portable Battery"
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/lml/loader.py:64: UserWarning: Deprecated! since version 0.0.3. Please use scan_plugins_regex!
  "Deprecated! since version 0.0.3. Please use scan_plugins_regex!"
I can cook Portable Battery for robots

Regards

**Comment by chfw** [comment]
Thanks for trying examples. Yes, can fix it.

**Comment by chansdad** [comment]
while you fix this. i am looking to use lml in production with scan_plugins function. Main reason for using lml is lazy loading and how easily i can add plugin functionality ..

**Comment by chfw** [comment]
to add a plugin is down to your design. lml provides a way to install, discover and load your plugin. 

Take pyexcel as an example, by default pyexcel provides csv, tsv read/write capability. To be able read and write xlsx, you install pyexcel-xlsx.

**Comment by markp2** [comment]
Hi, just hit this same issue:
[/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lml/loader.py:64: UserWarning: Deprecated! since version 0.0.3. Please use scan_plugins_regex!
  "Deprecated! since version 0.0.3. Please use scan_plugins_regex!"](url)

Looks like it is fixed (closed) in in cb74ea6 on 3 Apr –Any chance of a new release to resolve this? thanks!

**Comment by chfw** [comment]
It is a fix in examples, not in the library itself so I didn’t give it a release. How did it affect you?

**Comment by markp2** [comment]
I am using pyexcel.

In file: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyexcel/internal/__init__.py

At lIne 27:

[scan_plugins('pyexcel_', 'pyexcel', BLACK_LIST, WHITE_LIST)](url)

**Comment by markp2** [comment]
Apologies- looks like I was running an old [0.5.7] version of pyexcel. Upgrading to the latest 0.5.13 fixed this.

**Comment by chfw** [comment]
Alright then

**Comment by KeithTt** [comment]
> Apologies- looks like I was running an old [0.5.7] version of pyexcel. Upgrading to the latest 0.5.13 fixed this.

I checked my package version, it is `pyexcel==0.5.13`, but I still face this problem.

**Comment by chfw** [comment]
Please try 0.1.0
