### ISSUE TITLE
Tests not distributed for use by distro package validation

### ISSUE THREAD

**Issue by jayvdb** [chfw/lml#9]
I am building openSUSE packages for lml & moban at https://build.opensuse.org/project/show/home:jayvdb:soe , and noticed that the `tests` and `docs/source` are missing, so there is only one doctest running to validate the package.

If they are not too big, it would be good to include `tests` and `docs/source` in the source tarball.

Alternatively, a second tarball including those could be created during the release process, to be used by packagers.

(I expect I will encounter the same problem when polishing the package for moban)

**Comment by chfw** [comment]
First of all, thanks for your effort in taking this library to OpenSuse.

I was not aware that distro package validation is based on what's included in tar-ball. I will append these required content in it. Comparing other python package measured in MB, the additional content are small.

For moban, yep, it would need the additional content.

**Comment by chfw** [comment]
Please re-open if the new tar ball is not sufficient.

**Comment by jayvdb** [comment]
btw, I dont have permission to re-open here ;-)

Anyways, after https://github.com/chfw/lml/issues/11 , we now have green builds at https://build.opensuse.org/package/show/home:jayvdb:soe/python-lml

Thanks for your help.
